#!/usr/bin/env python3
"""Emit the compiled CTW adapter binding table from ABI-verified profiles."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re

import adapter_catalog
import profile_template


C_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

DEFAULT_CATALOG = (
    Path(__file__).resolve().parents[2]
    / "projects"
    / "gtactw-android-3d"
    / "adapter_catalog.json"
)


def adapters_from_profile(path: Path, catalog: dict) -> list[dict]:
    obj = json.loads(path.read_text(encoding="utf-8"))
    targets = obj.get("patch_targets_rva", {})
    target_ledger = obj.get("target_verification", {})
    abi_ledger = obj.get("abi_verification", {})

    readiness = adapter_catalog.validate_profile_adapters(obj, catalog)
    if not readiness["ready"]:
        missing = [
            key
            for key, item in readiness["targets"].items()
            if not item["ready"]
        ]
        raise ValueError(
            f"{path}: native adapters not ready for: " + ", ".join(missing)
        )

    out = []
    for key in profile_template.TARGET_KEYS:
        rva = targets.get(key)
        target = target_ledger.get(key)
        if not (
            isinstance(rva, int)
            and rva > 0
            and isinstance(target, dict)
            and target.get("status") == "verified"
            and target.get("rva") == rva
        ):
            raise ValueError(
                f"{path}: {key} target RVA must be verified before adapter emission"
            )

        abi = abi_ledger.get(key)
        if not isinstance(abi, dict) or abi.get("status") != "verified":
            raise ValueError(f"{path}: {key} ABI must have status=verified")

        adapter = abi.get("adapter")
        if not isinstance(adapter, str) or not adapter.strip():
            raise ValueError(f"{path}: {key} adapter name is required")

        catalog_item = readiness["targets"][key]["catalog_entry"]
        native_symbol = catalog_item.get("native_symbol")
        if not isinstance(native_symbol, str) or not C_IDENT_RE.fullmatch(
            native_symbol
        ):
            raise ValueError(
                f"{path}: {key} native_symbol must be a valid C identifier"
            )

        verified_rva = abi.get("verified_rva")
        if verified_rva is not None and verified_rva != rva:
            raise ValueError(
                f"{path}: {key} ABI verified_rva differs from target RVA"
            )

        evidence = abi.get("evidence")
        if not isinstance(evidence, list) or not evidence:
            raise ValueError(f"{path}: {key} ABI evidence is required")

        out.append({
            "target": key,
            "adapter": adapter,
            "native_symbol": native_symbol,
            "rva": rva,
        })
    return out


def emit_header(bindings: list[dict]) -> str:
    if not bindings:
        raise ValueError("at least one ABI-verified adapter binding is required")

    adapters = []
    seen_names = {}
    for item in bindings:
        name = item["adapter"]
        symbol = item["native_symbol"]
        previous = seen_names.get(name)
        if previous is not None and previous != symbol:
            raise ValueError(
                f"adapter {name} maps to multiple native symbols"
            )
        if previous is None:
            seen_names[name] = symbol
            adapters.append((name, symbol))

    lines = [
        "#pragma once",
        "",
        '#include "ctw_adapter_registry.h"',
        "",
        "/* Generated by tools/gtactw/adapter_emit_c.py. */",
    ]
    declared = set()
    for _, symbol in adapters:
        if symbol not in declared:
            declared.add(symbol)
            lines.append(f"extern void {symbol}(void);")

    lines += [
        "",
        "static const CtwAdapterBinding",
        "g_ctw_adapter_bindings_storage[] = {",
    ]
    for name, symbol in adapters:
        lines.append(
            f'    {{ "{name}", (void *)&{symbol} }},'
        )

    lines += [
        "};",
        "",
        "static const size_t g_ctw_adapter_bindings_count =",
        "    sizeof(g_ctw_adapter_bindings_storage) /",
        "    sizeof(g_ctw_adapter_bindings_storage[0]);",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("profiles", type=Path, nargs="+")
    ap.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    try:
        catalog = adapter_catalog.load_catalog(args.catalog)
        bindings = []
        for path in args.profiles:
            bindings.extend(adapters_from_profile(path, catalog))
        content = emit_header(bindings)
    except Exception as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, indent=2))
        return 2

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(content, encoding="utf-8")
    print(json.dumps({
        "ok": True,
        "profiles": len(args.profiles),
        "bindings": len(bindings),
        "unique_adapters": len({x["adapter"] for x in bindings}),
        "out": str(args.out),
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
