#!/usr/bin/env python3
"""Emit the compiled CTW adapter binding table from ABI-verified profiles."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re

import profile_template


C_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def adapters_from_profile(path: Path) -> list[dict]:
    obj = json.loads(path.read_text(encoding="utf-8"))
    targets = obj.get("patch_targets_rva", {})
    target_ledger = obj.get("target_verification", {})
    abi_ledger = obj.get("abi_verification", {})

    out = []
    for key in profile_template.TARGET_KEYS:
        rva = targets.get(key)
        target = target_ledger.get(key)
        if not (
            isinstance(rva, int)
            and rva > 0
            and isinstance(target, dict)
            and target.get("status") == "verified"
            and target.get("rva") == rva
        ):
            raise ValueError(
                f"{path}: {key} target RVA must be verified before adapter emission"
            )

        abi = abi_ledger.get(key)
        if not isinstance(abi, dict) or abi.get("status") != "verified":
            raise ValueError(f"{path}: {key} ABI must have status=verified")

        adapter = abi.get("adapter")
        if not isinstance(adapter, str) or not C_IDENT_RE.fullmatch(adapter):
            raise ValueError(
                f"{path}: {key} adapter must be a valid C identifier"
            )

        verified_rva = abi.get("verified_rva")
        if verified_rva is not None and verified_rva != rva:
            raise ValueError(
                f"{path}: {key} ABI verified_rva differs from target RVA"
            )

        evidence = abi.get("evidence")
        if not isinstance(evidence, list) or not evidence:
            raise ValueError(f"{path}: {key} ABI evidence is required")

        out.append({
            "target": key,
            "adapter": adapter,
            "rva": rva,
        })
    return out


def emit_header(bindings: list[dict]) -> str:
    if not bindings:
        raise ValueError("at least one ABI-verified adapter binding is required")

    adapters = []
    seen = set()
    for item in bindings:
        name = item["adapter"]
        if name not in seen:
            seen.add(name)
            adapters.append(name)

    lines = [
        "#pragma once",
        "",
        '#include "ctw_adapter_registry.h"',
        "",
        "/* Generated by tools/gtactw/adapter_emit_c.py. */",
    ]
    for name in adapters:
        lines.append(f"extern void {name}(void);")

    lines += [
        "",
        "static const CtwAdapterBinding",
        "g_ctw_adapter_bindings_storage[] = {",
    ]
    for name in adapters:
        lines.append(f'    {{ "{name}", (void *)&{name} }},')

    lines += [
        "};",
        "",
        "static const size_t g_ctw_adapter_bindings_count =",
        "    sizeof(g_ctw_adapter_bindings_storage) /",
        "    sizeof(g_ctw_adapter_bindings_storage[0]);",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("profiles", type=Path, nargs="+")
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    try:
        bindings = []
        for path in args.profiles:
            bindings.extend(adapters_from_profile(path))
        content = emit_header(bindings)
    except Exception as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, indent=2))
        return 2

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(content, encoding="utf-8")
    print(json.dumps({
        "ok": True,
        "profiles": len(args.profiles),
        "bindings": len(bindings),
        "unique_adapters": len({x["adapter"] for x in bindings}),
        "out": str(args.out),
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
