#!/usr/bin/env python3
"""Emit ctw_profiles_generated.h from one or more verified CTW profile JSON files."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

TARGET_KEYS = (
    "camera_update",
    "projection_setup",
    "world_stream_update",
    "sector_visibility",
    "lod_test",
    "player_render",
)


def require_rva(value, label: str) -> int:
    if not isinstance(value, int) or value <= 0:
        raise ValueError(f"{label} must be a positive integer RVA")
    return value


def load_verified_profile(path: Path) -> dict:
    obj = json.loads(path.read_text(encoding="utf-8"))
    fp = obj.get("fingerprint", {})
    jni = fp.get("jni_rvas", {})
    targets = obj.get("patch_targets_rva", {})

    draw = require_rva(jni.get("implOnDrawFrame"), "implOnDrawFrame RVA")
    setup = require_rva(jni.get("implOnInitialSetup"), "implOnInitialSetup RVA")
    axes = require_rva(
        jni.get("implOnGamepadAxesChanged"),
        "implOnGamepadAxesChanged RVA",
    )
    clean_targets = {
        key: require_rva(targets.get(key), f"{key} RVA")
        for key in TARGET_KEYS
    }

    verification = obj.get("target_verification", {})
    for key in TARGET_KEYS:
        item = verification.get(key)
        if not isinstance(item, dict):
            raise ValueError(f"{key} verification record is required")
        if item.get("status") != "verified":
            raise ValueError(f"{key} must have status=verified")
        verified_rva = require_rva(item.get("rva"), f"{key} verified RVA")
        if verified_rva != clean_targets[key]:
            raise ValueError(
                f"{key} verification RVA does not match patch_targets_rva"
            )
        evidence = item.get("evidence")
        if not isinstance(evidence, list) or not evidence:
            raise ValueError(f"{key} must contain at least one evidence record")
        for index, ev in enumerate(evidence):
            if not isinstance(ev, dict):
                raise ValueError(f"{key} evidence[{index}] must be an object")
            method = ev.get("method")
            detail = ev.get("detail")
            if not isinstance(method, str) or not method.strip():
                raise ValueError(f"{key} evidence[{index}] needs method")
            if not isinstance(detail, str) or not detail.strip():
                raise ValueError(f"{key} evidence[{index}] needs detail")

    sha = fp.get("sha256")
    if not isinstance(sha, str) or len(sha) != 64:
        raise ValueError("profile must contain a 64-character libGame SHA-256")

    return {
        "name": f"{path.stem}:{sha[:12]}",
        "draw": draw,
        "setup": setup,
        "axes": axes,
        "targets": clean_targets,
    }


def emit_header(profiles: list[dict]) -> str:
    if not profiles:
        raise ValueError("at least one verified profile is required")

    seen = set()
    for p in profiles:
        key = (p["draw"], p["setup"], p["axes"])
        if key in seen:
            raise ValueError(
                "duplicate runtime fingerprint: "
                f"draw=0x{key[0]:X} setup=0x{key[1]:X} axes=0x{key[2]:X}"
            )
        seen.add(key)

    lines = [
        "#pragma once",
        "",
        '#include "ctw_profile.h"',
        "",
        "/* Generated by tools/gtactw/profile_emit_c.py. */",
        "static const CtwBuildProfile g_ctw_profiles_storage[] = {",
    ]

    for p in profiles:
        t = p["targets"]
        lines += [
            "    {",
            f'        .name = "{p["name"]}",',
            f'        .expected_draw_frame_rva = 0x{p["draw"]:X}u,',
            f'        .expected_initial_setup_rva = 0x{p["setup"]:X}u,',
            f'        .expected_gamepad_axes_rva = 0x{p["axes"]:X}u,',
            "        .target_rvas = {",
            f'            .camera_update = 0x{t["camera_update"]:X}u,',
            f'            .projection_setup = 0x{t["projection_setup"]:X}u,',
            f'            .world_stream_update = 0x{t["world_stream_update"]:X}u,',
            f'            .sector_visibility = 0x{t["sector_visibility"]:X}u,',
            f'            .lod_test = 0x{t["lod_test"]:X}u,',
            f'            .player_render = 0x{t["player_render"]:X}u,',
            "        },",
            "    },",
        ]

    lines += [
        "};",
        "",
        "static const size_t g_ctw_profiles_count =",
        "    sizeof(g_ctw_profiles_storage) / sizeof(g_ctw_profiles_storage[0]);",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("profiles", type=Path, nargs="+")
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    try:
        profiles = [load_verified_profile(p) for p in args.profiles]
        content = emit_header(profiles)
    except Exception as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, indent=2))
        return 2

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(content, encoding="utf-8")
    print(json.dumps({"ok": True, "profiles": len(profiles), "out": str(args.out)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
