#!/usr/bin/env python3
"""Generate the native Nacht BO3 Mystery Box pool from validated JSON authority."""

from __future__ import annotations

import json
from pathlib import Path

CATALOG = Path("assets/weapons/xziel_weapon_catalog_v1.json")
POOL = Path("assets/weapons/nacht_prototype_box_pool_v1.json")
OUT = Path("engine/xz/xz_nacht_mystery_box_pool.generated.inc")

EXPECTED_COUNT = 34


def c_string(value: str | None) -> str:
    if value is None:
        return "NULL"
    return json.dumps(value)


def main() -> int:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    pool = json.loads(POOL.read_text(encoding="utf-8"))

    if pool.get("mapId") != "xziel_nacht_bo3":
        raise SystemExit("Nacht box pool mapId mismatch")
    if pool.get("policy") != "exact_zm_prototype_in_box_membership":
        raise SystemExit("Nacht box pool policy mismatch")

    weapon_ids = pool.get("weaponIds", [])
    if len(weapon_ids) != EXPECTED_COUNT:
        raise SystemExit(
            f"Nacht box pool count mismatch: {len(weapon_ids)} != {EXPECTED_COUNT}"
        )
    if len(set(weapon_ids)) != len(weapon_ids):
        raise SystemExit("Nacht box pool contains duplicate weapon IDs")

    by_id = {
        row["weaponId"]: row
        for row in catalog.get("weapons", [])
    }

    lines = [
        "/*",
        " * AUTO-GENERATED by tools/weapons/generate_nacht_mystery_box_runtime.py",
        " * Source membership: assets/weapons/nacht_prototype_box_pool_v1.json",
        " * Do not hand-edit. Regenerate and validate instead.",
        " */",
    ]

    for weapon_id in weapon_ids:
        row = by_id.get(weapon_id)
        if row is None:
            raise SystemExit(f"Nacht box weapon absent from catalog: {weapon_id}")

        proto = row.get("nachtPrototype", {})
        if proto.get("present") is not True or proto.get("inBox") is not True:
            raise SystemExit(
                f"Nacht box weapon lacks prototype in-box authority: {weapon_id}"
            )

        upgrade = proto.get("upgradeId")
        is_limited = proto.get("isLimited") is True
        raw_limit = proto.get("limit")
        limit_defined = isinstance(raw_limit, int)
        limit = raw_limit if limit_defined else 0

        if limit_defined and limit <= 0:
            raise SystemExit(
                f"Invalid positive limited quota for {weapon_id}: {raw_limit}"
            )

        lines.append(
            "    {"
            f"{c_string(weapon_id)}, "
            f"{c_string(upgrade)}, "
            f"{1 if is_limited else 0}u, "
            f"{1 if limit_defined else 0}u, "
            f"{limit}u"
            "},"
        )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"XZIEL_NACHT_BOX_NATIVE_POOL_OK count={len(weapon_ids)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
